name: Build

on:
  push:
    branches:
      - master
      - test-actions
  release:
    types: [ created ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    name: Build
    runs-on: windows-latest

    strategy:
      matrix:
        buildpreset: 
        - Release

    steps:
    - name: Get latest CMake and ninja
      uses: lukka/get-cmake@latest

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup VS environment
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: get ZHMModSDK commit hash
      run: |
        echo "ZHMModSDK_COMMIT=$(git submodule status External/ZHMModSDK)" >> $GITHUB_OUTPUT

    - name: Cache SDK
      id: cache-sdk
      uses: actions/cache@v3
      with:
        path: External/ZHMModSDK
        key: ZHMModSDK_${{ env.ZHMModSDK_COMMIT }}

    - name: Generate SDK projects
      if: steps.cache-sdk.outputs.cache-hit != 'true'
      working-directory: External/ZHMModSDK
      run: |
        cmake --preset x64-${{ matrix.buildpreset }} .

    - name: Build SDK
      if: steps.cache-sdk.outputs.cache-hit != 'true'
      working-directory: External/ZHMModSDK
      run: |
        cmake --build _build/x64-${{ matrix.buildpreset }} --target install


    - name: Generate Mod projects
      run: |
        cmake --preset x64-${{ matrix.buildpreset }} .

    - name: Build Mod
      run: |
        cmake --build _build/x64-${{ matrix.buildpreset }}

    - name: Archive Mod dll
      uses: actions/upload-artifact@v2
      with:
        name: ImmersiveAssassination.dll
        path: _build/x64-${{ matrix.buildpreset }}/ImmersiveAssassination.dll
